# Generated by Django 4.1.5 on 2023-02-13 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productMainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('unique_code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_number', models.CharField(max_length=15, unique=True)),
                ('Email', models.EmailField(max_length=254)),
                ('is_customer', models.BinaryField(blank=True, editable=True, null=True)),
                ('is_admin', models.BinaryField(blank=True, editable=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userProfileModel',
            fields=[
                ('User_Model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.user_model')),
                ('Gender_choice', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], max_length=10)),
                ('Image', models.ImageField(default=True, upload_to='bat_imgs/')),
            ],
        ),
        migrations.CreateModel(
            name='productImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default=True, upload_to='bat_imgs/')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.productmainmodel')),
            ],
        ),
    ]
