# Generated by Django 4.1.5 on 2023-02-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_model_is_admin_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productColourModel',
            new_name='getproduct',
        ),
    ]
